import Foundation

/// Exports current reminder rules as a Cursor skill file.
/// Cursor auto-loads all `~/.cursor/skills/**` SKILL.md files — no mcp.json config needed.
/// The skill tells the AI what rules exist and how to interact via the embedded HTTP API.
struct ReminderSkillExporter {

    static let skillDir = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".cursor/skills/magicer-reminders")

    // MARK: - Public API

    /// Export (or refresh) the skill file. Called automatically on rules change.
    @discardableResult
    static func export(rules: [ReminderRule]) -> Bool {
        let content = buildSkill(rules: rules)
        do {
            try FileManager.default.createDirectory(at: skillDir,
                                                    withIntermediateDirectories: true)
            let url = skillDir.appendingPathComponent("SKILL.md")
            try content.write(to: url, atomically: true, encoding: .utf8)
            return true
        } catch {
            return false
        }
    }

    // MARK: - Skill content

    private static func buildSkill(rules: [ReminderRule]) -> String {
        let iso = ISO8601DateFormatter()
        var s = ""

        s += """
        # Magicer 定时提醒 — AI Skill

        Use this skill whenever the user wants to **view, add, modify, or delete** reminder rules
        running in the Magicer app on their Mac.

        ---

        ## Current Rules  *(auto-synced on every save)*\n
        """

        if rules.isEmpty {
            s += "_No rules configured._\n"
        } else {
            for r in rules {
                let status = r.isEnabled ? "✅" : "⏸"
                s += "\n### \(status) \(r.name)\n"
                s += "- id: `\(r.id)`\n"
                switch r.triggerMode {
                case .interval:
                    s += "- trigger: every **\(r.intervalMinutes) minutes**\n"
                case .scheduled:
                    let times = r.scheduledTimes.map { $0.displayText }.joined(separator: ", ")
                    s += "- trigger: daily @ **\(times.isEmpty ? "(no times set)" : times)**\n"
                case .once:
                    s += "- trigger: once @ **\(iso.string(from: r.onceDate))**\n"
                }
                if r.followupMinutes > 0 {
                    s += "- followup: \(r.followupMinutes) min after dismissal\n"
                }
                s += "- overlay text: \"\(r.reminderText)\"\n"
                s += "- duration: \(r.durationSeconds)s · theme: \(r.themeId)\n"
            }
        }

        s += """

        ---

        ## How to Interact

        Magicer runs an embedded HTTP server on **`http://127.0.0.1:18879`** while the app is open.
        Dates use ISO 8601 (e.g. `2026-04-15T09:00:00Z`).

        ### Read
        ```bash
        curl http://127.0.0.1:18879/reminders
        ```

        ### Add a rule
        ```bash
        curl -X POST http://127.0.0.1:18879/reminders \\
          -H 'Content-Type: application/json' \\
          -d '{
            "id": "<generate a UUID>",
            "name": "喝水提醒",
            "triggerMode": "interval",
            "intervalMinutes": 60,
            "scheduledTimes": [],
            "onceDate": "2026-04-15T09:00:00Z",
            "followupMinutes": 0,
            "durationSeconds": 10,
            "canCloseImmediately": false,
            "reminderText": "该喝水了！",
            "themeId": "blue-calm",
            "isEnabled": true
          }'
        ```

        ### Toggle enabled/disabled
        ```bash
        curl -X PUT http://127.0.0.1:18879/reminders/{id}/toggle
        ```

        ### Delete
        ```bash
        curl -X DELETE http://127.0.0.1:18879/reminders/{id}
        ```

        ### triggerMode values
        | value | meaning |
        | --- | --- |
        | `interval` | repeat every N minutes |
        | `scheduled` | fire at specific times each day (use `scheduledTimes`) |
        | `once` | fire once at `onceDate`, then auto-disable |

        ### Available themeIds
        `red-alarm` · `blue-calm` · `green-focus` · `purple-zen` · `orange-energy`
        *(Use `curl http://127.0.0.1:18879/reminders` to see themes in use.)*

        ---

        > Auto-generated by Magicer · Synced: \(iso.string(from: Date()))
        """

        return s
    }
}
